---
- name: Create initial cluster
  hosts: initial
  tasks:
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "ansible-role-openhpc/"
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups['testohpc_login'] }}"
          batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
          runtime: true
        openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
        openhpc_slurm_partitions:
          - name: "compute"
        openhpc_cluster_name: testohpc
        openhpc_slurm_configless: true
    - name: Get cluster info
      shell:
        cmd: sinfo
      register:
        original_sinfo
      run_once: true
    - debug:
        msg: "{{ original_sinfo.stdout_lines }}"
      run_once: true
    
- name: Add new host(s)
  hosts:
    - testohpc_login
    - new
  tasks:
    - name: Add new host(s) to testohpc_compute group
      add_host:
        name: "{{ item }}"
        groups: testohpc_compute
      loop: "{{ groups['new'] }}"
      run_once: true
    - name: "Include ansible-role-openhpc"
      include_role:
        name: "ansible-role-openhpc/"
      vars:
        openhpc_enable:
          control: "{{ inventory_hostname in groups['testohpc_login'] }}"
          batch: "{{ inventory_hostname in groups['testohpc_compute'] }}"
          runtime: true
        openhpc_slurm_control_host: "{{ groups['testohpc_login'] | first }}"
        openhpc_slurm_partitions:
          - name: "compute"
        openhpc_cluster_name: testohpc
        openhpc_slurm_configless: true
    - name: Get cluster info
      shell:
        cmd: sinfo
      register:
        original_sinfo
      run_once: true
    - debug:
        msg: "{{ original_sinfo.stdout_lines }}"
      run_once: true
